version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=northwind
      - POSTGRES_USER=northwindUser
      - POSTGRES_PASSWORD=northwindPass
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data